version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: dev
    volumes:
      - .:/workspace:Z
    command:
      - sleep
      - infinity
    platform: linux/amd64
